export const SET_FIELD_ANSWER = 'SET_FIELD_ANSWER';
export const INSERT_EMPTY_FIELD_ANSWER = 'INSERT_EMPTY_FIELD_ANSWER';
export const SET_IS_FIELD_VALID = 'SET_IS_FIELD_VALID';
export const SET_IS_FIELD_ANSWERED = 'SET_IS_FIELD_ANSWERED';
export const SET_SHOW_FIELD_ERR = 'SET_SHOW_FIELD_ERR';
export const SET_FIELD_ERR_MSG_KEY = 'SET_FIELD_ERR_MSG_KEY';
