export const SET_THEME_PROPERTIES = 'SET_THEME_PROPERTIES';
export const SET_SHOULD_BE_SAVED = 'SET_SHOULD_BE_SAVED';
export const SET_CURRENT_THEME_ID = 'SET_CURRENT_THEME_ID';
export const SETUP_STORE = 'SETUP_STORE';
export const ADD_NEW_THEME = 'ADD_NEW_THEME';
export const UPDATE_THEME = 'UPDATE_THEME';
