export const REGISTER_BUILDER_PANEL = 'REGISTER_BUILDER_PANEL';
export const REGISTER_BUILDER_SUBPANEL = 'REGISTER_BUILDER_SUBPANEL';
export const SET_CURRENT_PANEL = 'SET_CURRENT_PANEL';
export const SET_CURRENT_SUBPANEL = 'SET_CURRENT_SUBPANEL';
export const STORE_KEY = 'quillForms/builder-panels';
