export const SET_BLOCK_RENDERER_SETTINGS = 'SET_BLOCK_RENDERER_SETTINGS';
export const SET_BLOCK_ADMIN_SETTINGS = 'SET_BLOCK_ADMIN_SETTINGS';
export const REGISTER_SERVER_SIDE_BLOCKS = 'REGISTER_SERVER_SIDE_BLOCKS';
