export const SET_BLOCK_RENDERER_CONFIG = 'SET_BLOCK_RENDERER_CONFIG';
export const SET_BLOCK_EDITOR_CONFIG = 'SET_BLOCK_EDITOR_CONFIG';
export const REGISTER_SERVER_SIDE_BLOCKS = 'REGISTER_SERVER_SIDE_BLOCKS';
