export const DISABLE_PROGRESS_BAR = 'DISABLE_PROGRESS_BAR';
export const DISABLE_WHEEL_SWIPING = 'DISABLE_WHEEL_SWIPING';
export const DISABLE_NAVIGATION_ARROWS = 'DISABLE_NAVIGATION_ARROWS';
export const CHANGE_ANIMATION_DIRECTION = 'CHANGE_ANIMATION_DIRECTION';
export const SHOW_QUESTIONS_NUMBERS = 'SHOW_QUESTIONS_NUMBERS';
export const SHOW_LETTERS_ON_ANSWERS = 'SHOW_LETTERS_ON_ANSWERS';
export const SETUP_STORE = 'SETUP_STORE';
