export const DISABLE_PROGRESS_BAR = 'DISABLE_PROGRESS_BAR';
export const DISABLE_WHEEL_SWIPING = 'DISABLE_WHEEL_SWIPING';
export const DISABLE_NAVIGATION_ARROWS = 'DISABLE_NAVIGATION_ARROWS';
export const CHANGE_ANIMATION_DIRECTION = 'CHANGE_ANIMATION_DIRECTION';
export const SETUP_STORE = 'SETUP_STORE';
