export const SET_CORRECT_INCORRECT_QUIZ_MODE = 'SET_CORRECT_INCORRECT_QUIZ_MODE';
export const SET_CORRECT_ANSWERS = 'SET_CORRECT_ANSWERS';
export const SHOW_ANSWER_CORRECT_INCORRECT = 'SHOW_CORRECT_ANSWER';
