export const TOGGLE_CORRECT_INCORRECT_QUIZ_MODE = 'TOGGLE_CORRECT_INCORRECT_QUIZ_MODE';
export const SET_CORRECT_ANSWERS = 'SET_CORRECT_ANSWERS';
export const SHOW_ANSWERS_DURING_QUIZ = 'SHOW_ANSWERS_DURING_QUIZ';
export const SETUP_STORE = 'SETUP_STORE';