// @ts-ignore
import './blocks/date';
// @ts-ignore
import './blocks/dropdown';
// @ts-ignore
import './blocks/email';
// @ts-ignore
import './blocks/long-text';
// @ts-ignore
import './blocks/multiple-choice';
// @ts-ignore
import './blocks/number';
// @ts-ignore
import './blocks/short-text';
// @ts-ignore
import './blocks/statement';
// @ts-ignore
import './blocks/website';
// @ts-ignore
import './blocks/welcome-screen';
