export const SET_IS_BLOCK_CHANGING = 'SET_IS_BLOCK_CHANGING';
export const SET_CURRENT_BLOCK = 'SET_CURRENT_BLOCK';
export const SET_CAN_NEXT = 'SET_CAN_NEXT';
export const SET_CAN_PREV = 'SET_CAN_PREV';
export const SET_ANIMATION_EFFECTS = 'SET_ANIMATION_EFFECTS';
