export const SET_CURRENT_BLOCK_ID = 'SET_CURRENT_BLOCK_ID';
export const SET_NEXT_BLOCK_ID = 'SET_NEXT_BLOCK_ID';
export const SET_PREV_BLOCK_ID = 'SET_PREV_BLOCK_ID';
export const SET_LAST_ACTIVE_BLOCK_ID = 'SET_LAST_ACTIVE_BLOCK_ID';
export const SET_CURRENT_PATH = 'SET_CURRENT_PATH';
