export const SETUP_STORE = 'SETUP_STORE';
export const SET_NOTIFICATION_PROPERTIES = 'SET_NOTIFICATION_PROPERTIES';
export const ADD_NEW_NOTIFICATION = 'ADD_NEW_NOTIFICATION';
export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION';
