<?php
/**
 * Class: Payments
 *
 * @since 1.8.0
 * @package QuillForms
 */

namespace QuillForms;

/**
 * Payments Class
 *
 * @since 1.8.0
 */
class Payments {

	/**
	 * Class instance
	 *
	 * @since 1.8.0
	 *
	 * @var self instance
	 */
	private static $instance = null;

	/**
	 * Get class instance
	 *
	 * @since 1.8.0
	 *
	 * @return self
	 */
	public static function instance() {
		if ( ! self::$instance ) {
			self::$instance = new self();
		}
		return self::$instance;
	}

	/**
	 * Constructor
	 *
	 * @since 1.8.0
	 */
	private function __construct() {}

	/**
	 * Get currencies
	 *
	 * @since 1.8.0
	 *
	 * @return array
	 */
	public function get_currencies() {
		return apply_filters( 'quillforms_currencies', $this->get_default_currencies() );
	}

	/**
	 * Get default currencies
	 *
	 * @since 1.8.0
	 *
	 * @return array
	 */
	private function get_default_currencies() {
		return array(
			'AFN' => array(
				'name'         => 'Afghan afghani',
				'singular'     => 'Afghan Afghani',
				'plural'       => 'Afghan Afghanis',
				'symbol'       => '؋',
				'symbol_pos'   => 'left_space',
				'num_decimals' => 0,
				'decimal_sep'  => ',',
				'thousand_sep' => '.',
			),
			'ALL' => array(
				'name'         => 'Albanian lek',
				'singular'     => 'Albanian lek',
				'plural'       => 'Albanian lekë',
				'symbol'       => null,
				'symbol_pos'   => 'right_space',
				'num_decimals' => 0,
				'decimal_sep'  => ',',
				'thousand_sep' => ' ',
			),
			'DZD' => array(
				'name'         => 'Algerian dinar',
				'singular'     => 'Algerian dinar',
				'plural'       => 'Algerian dinars',
				'symbol'       => null,
				'symbol_pos'   => 'left_space',
				'num_decimals' => 2,
				'decimal_sep'  => ',',
				'thousand_sep' => '.',
			),
			'AOA' => array(
				'name'         => 'Angolan kwanza',
				'singular'     => 'Angolan kwanza',
				'plural'       => 'Angolan kwanzas',
				'symbol'       => 'Kz',
				'symbol_pos'   => 'right_space',
				'num_decimals' => 2,
				'decimal_sep'  => ',',
				'thousand_sep' => ' ',
			),
			'ARS' => array(
				'name'         => 'Argentine peso',
				'singular'     => 'Argentine peso',
				'plural'       => 'Argentine pesos',
				'symbol'       => '$',
				'symbol_pos'   => 'left_space',
				'num_decimals' => 2,
				'decimal_sep'  => ',',
				'thousand_sep' => '.',
			),
			'AMD' => array(
				'name'         => 'Armenian dram',
				'singular'     => 'Armenian dram',
				'plural'       => 'Armenian drams',
				'symbol'       => '֏',
				'symbol_pos'   => 'right_space',
				'num_decimals' => 0,
				'decimal_sep'  => ',',
				'thousand_sep' => ' ',
			),
			'AWG' => array(
				'name'         => 'Aruban florin',
				'singular'     => 'Aruban florin',
				'plural'       => 'Aruban florin',
				'symbol'       => null,
				'symbol_pos'   => 'left_space',
				'num_decimals' => 2,
				'decimal_sep'  => ',',
				'thousand_sep' => '.',
			),
			'AUD' => array(
				'name'         => 'Australian dollar',
				'singular'     => 'Australian dollar',
				'plural'       => 'Australian dollars',
				'symbol'       => '$',
				'symbol_pos'   => 'left',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'AZN' => array(
				'name'         => 'Azerbaijani manat',
				'singular'     => 'Azerbaijani manat',
				'plural'       => 'Azerbaijani manats',
				'symbol'       => '₼',
				'symbol_pos'   => 'right_space',
				'num_decimals' => 2,
				'decimal_sep'  => ',',
				'thousand_sep' => '.',
			),
			'BSD' => array(
				'name'         => 'Bahamian dollar',
				'singular'     => 'Bahamian dollar',
				'plural'       => 'Bahamian dollars',
				'symbol'       => '$',
				'symbol_pos'   => 'left',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'BHD' => array(
				'name'         => 'Bahraini dinar',
				'singular'     => 'Bahraini dinar',
				'plural'       => 'Bahraini dinars',
				'symbol'       => null,
				'symbol_pos'   => 'right_space',
				'num_decimals' => 3,
				'decimal_sep'  => ',',
				'thousand_sep' => '.',
			),
			'BDT' => array(
				'name'         => 'Bangladeshi taka',
				'singular'     => 'Bangladeshi taka',
				'plural'       => 'Bangladeshi takas',
				'symbol'       => '৳',
				'symbol_pos'   => 'right',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'BBD' => array(
				'name'         => 'Barbadian dollar',
				'singular'     => 'Barbadian dollar',
				'plural'       => 'Barbadian dollars',
				'symbol'       => '$',
				'symbol_pos'   => 'left',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'BYN' => array(
				'name'         => 'Belarusian ruble',
				'singular'     => 'Belarusian ruble',
				'plural'       => 'Belarusian rubles',
				'symbol'       => 'р.',
				'symbol_pos'   => 'right_space',
				'num_decimals' => 2,
				'decimal_sep'  => ',',
				'thousand_sep' => ' ',
			),
			'BZD' => array(
				'name'         => 'Belize dollar',
				'singular'     => 'Belize dollar',
				'plural'       => 'Belize dollars',
				'symbol'       => '$',
				'symbol_pos'   => 'left',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'BMD' => array(
				'name'         => 'Bermudian dollar',
				'singular'     => 'Bermudan dollar',
				'plural'       => 'Bermudan dollars',
				'symbol'       => '$',
				'symbol_pos'   => 'left',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'BTN' => array(
				'name'         => 'Bhutanese ngultrum',
				'singular'     => 'Bhutanese ngultrum',
				'plural'       => 'Bhutanese ngultrums',
				'symbol'       => null,
				'symbol_pos'   => 'left',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'BOB' => array(
				'name'         => 'Bolivian boliviano',
				'singular'     => 'Bolivian boliviano',
				'plural'       => 'Bolivian bolivianos',
				'symbol'       => 'Bs',
				'symbol_pos'   => 'left',
				'num_decimals' => 2,
				'decimal_sep'  => ',',
				'thousand_sep' => '.',
			),
			'VES' => array(
				'name'         => 'Bolívar soberano',
				'singular'     => 'Venezuelan bolívar',
				'plural'       => 'Venezuelan bolívars',
				'symbol'       => null,
				'symbol_pos'   => 'left',
				'num_decimals' => 2,
				'decimal_sep'  => ',',
				'thousand_sep' => '.',
			),
			'BAM' => array(
				'name'         => 'Bosnia and Herzegovina convertible mark',
				'singular'     => 'Bosnia-Herzegovina convertible mark',
				'plural'       => 'Bosnia-Herzegovina convertible marks',
				'symbol'       => 'KM',
				'symbol_pos'   => 'right_space',
				'num_decimals' => 2,
				'decimal_sep'  => ',',
				'thousand_sep' => '.',
			),
			'BWP' => array(
				'name'         => 'Botswana pula',
				'singular'     => 'Botswanan pula',
				'plural'       => 'Botswanan pulas',
				'symbol'       => 'P',
				'symbol_pos'   => 'left',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'BRL' => array(
				'name'         => 'Brazilian real',
				'singular'     => 'Brazilian real',
				'plural'       => 'Brazilian reals',
				'symbol'       => 'R$',
				'symbol_pos'   => 'left_space',
				'num_decimals' => 2,
				'decimal_sep'  => ',',
				'thousand_sep' => '.',
			),
			'BND' => array(
				'name'         => 'Brunei dollar',
				'singular'     => 'Brunei dollar',
				'plural'       => 'Brunei dollars',
				'symbol'       => '$',
				'symbol_pos'   => 'left_space',
				'num_decimals' => 2,
				'decimal_sep'  => ',',
				'thousand_sep' => '.',
			),
			'BGN' => array(
				'name'         => 'Bulgarian lev',
				'singular'     => 'Bulgarian lev',
				'plural'       => 'Bulgarian leva',
				'symbol'       => null,
				'symbol_pos'   => 'right_space',
				'num_decimals' => 2,
				'decimal_sep'  => ',',
				'thousand_sep' => ' ',
			),
			'MMK' => array(
				'name'         => 'Burmese kyat',
				'singular'     => 'Myanmar kyat',
				'plural'       => 'Myanmar kyats',
				'symbol'       => 'K',
				'symbol_pos'   => 'right_space',
				'num_decimals' => 0,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'BIF' => array(
				'name'         => 'Burundian franc',
				'singular'     => 'Burundian franc',
				'plural'       => 'Burundian francs',
				'symbol'       => null,
				'symbol_pos'   => 'right',
				'num_decimals' => 0,
				'decimal_sep'  => ',',
				'thousand_sep' => '.',
			),
			'XPF' => array(
				'name'         => 'CFP franc',
				'singular'     => 'CFP franc',
				'plural'       => 'CFP francs',
				'symbol'       => null,
				'symbol_pos'   => 'right_space',
				'num_decimals' => 0,
				'decimal_sep'  => ',',
				'thousand_sep' => ' ',
			),
			'KHR' => array(
				'name'         => 'Cambodian riel',
				'singular'     => 'Cambodian riel',
				'plural'       => 'Cambodian riels',
				'symbol'       => '៛',
				'symbol_pos'   => 'right',
				'num_decimals' => 2,
				'decimal_sep'  => ',',
				'thousand_sep' => '.',
			),
			'CAD' => array(
				'name'         => 'Canadian dollar',
				'singular'     => 'Canadian dollar',
				'plural'       => 'Canadian dollars',
				'symbol'       => '$',
				'symbol_pos'   => 'left',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'CVE' => array(
				'name'         => 'Cape Verdean escudo',
				'singular'     => 'Cape Verdean escudo',
				'plural'       => 'Cape Verdean escudos',
				'symbol'       => null,
				'symbol_pos'   => 'right_space',
				'num_decimals' => 2,
				'decimal_sep'  => ',',
				'thousand_sep' => ' ',
			),
			'KYD' => array(
				'name'         => 'Cayman Islands dollar',
				'singular'     => 'Cayman Islands dollar',
				'plural'       => 'Cayman Islands dollars',
				'symbol'       => '$',
				'symbol_pos'   => 'left',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'XAF' => array(
				'name'         => 'Central African CFA franc',
				'singular'     => 'Central African CFA franc',
				'plural'       => 'Central African CFA francs',
				'symbol'       => null,
				'symbol_pos'   => 'right_space',
				'num_decimals' => 0,
				'decimal_sep'  => ',',
				'thousand_sep' => ' ',
			),
			'CLP' => array(
				'name'         => 'Chilean peso',
				'singular'     => 'Chilean peso',
				'plural'       => 'Chilean pesos',
				'symbol'       => '$',
				'symbol_pos'   => 'left',
				'num_decimals' => 0,
				'decimal_sep'  => ',',
				'thousand_sep' => '.',
			),
			'CNY' => array(
				'name'         => 'Chinese yuan',
				'singular'     => 'Chinese yuan',
				'plural'       => 'Chinese yuan',
				'symbol'       => '¥',
				'symbol_pos'   => 'left',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'COP' => array(
				'name'         => 'Colombian peso',
				'singular'     => 'Colombian peso',
				'plural'       => 'Colombian pesos',
				'symbol'       => '$',
				'symbol_pos'   => 'left_space',
				'num_decimals' => 0,
				'decimal_sep'  => ',',
				'thousand_sep' => '.',
			),
			'KMF' => array(
				'name'         => 'Comorian franc',
				'singular'     => 'Comorian franc',
				'plural'       => 'Comorian francs',
				'symbol'       => 'CF',
				'symbol_pos'   => 'right_space',
				'num_decimals' => 0,
				'decimal_sep'  => ',',
				'thousand_sep' => '.',
			),
			'CDF' => array(
				'name'         => 'Congolese franc',
				'singular'     => 'Congolese franc',
				'plural'       => 'Congolese francs',
				'symbol'       => null,
				'symbol_pos'   => 'left_space',
				'num_decimals' => 2,
				'decimal_sep'  => ',',
				'thousand_sep' => '.',
			),
			'CRC' => array(
				'name'         => 'Costa Rican colón',
				'singular'     => 'Costa Rican colón',
				'plural'       => 'Costa Rican colóns',
				'symbol'       => '₡',
				'symbol_pos'   => 'left',
				'num_decimals' => 0,
				'decimal_sep'  => ',',
				'thousand_sep' => ' ',
			),
			'HRK' => array(
				'name'         => 'Croatian kuna',
				'singular'     => 'Croatian kuna',
				'plural'       => 'Croatian kunas',
				'symbol'       => 'kn',
				'symbol_pos'   => 'right_space',
				'num_decimals' => 2,
				'decimal_sep'  => ',',
				'thousand_sep' => '.',
			),
			'CUC' => array(
				'name'         => 'Cuban convertible peso',
				'singular'     => 'Cuban convertible peso',
				'plural'       => 'Cuban convertible pesos',
				'symbol'       => '$',
				'symbol_pos'   => 'left',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'CZK' => array(
				'name'         => 'Czech koruna',
				'singular'     => 'Czech koruna',
				'plural'       => 'Czech korunas',
				'symbol'       => 'Kč',
				'symbol_pos'   => 'right_space',
				'num_decimals' => 0,
				'decimal_sep'  => ',',
				'thousand_sep' => ' ',
			),
			'DKK' => array(
				'name'         => 'Danish krone',
				'singular'     => 'Danish krone',
				'plural'       => 'Danish kroner',
				'symbol'       => 'kr',
				'symbol_pos'   => 'right_space',
				'num_decimals' => 2,
				'decimal_sep'  => ',',
				'thousand_sep' => '.',
			),
			'DJF' => array(
				'name'         => 'Djiboutian franc',
				'singular'     => 'Djiboutian franc',
				'plural'       => 'Djiboutian francs',
				'symbol'       => null,
				'symbol_pos'   => 'right_space',
				'num_decimals' => 0,
				'decimal_sep'  => ',',
				'thousand_sep' => '.',
			),
			'DOP' => array(
				'name'         => 'Dominican peso',
				'singular'     => 'Dominican peso',
				'plural'       => 'Dominican pesos',
				'symbol'       => '$',
				'symbol_pos'   => 'left',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'XCD' => array(
				'name'         => 'East Caribbean dollar',
				'singular'     => 'East Caribbean dollar',
				'plural'       => 'East Caribbean dollars',
				'symbol'       => '$',
				'symbol_pos'   => 'left',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'EGP' => array(
				'name'         => 'Egyptian pound',
				'singular'     => 'Egyptian pound',
				'plural'       => 'Egyptian pounds',
				'symbol'       => 'E£',
				'symbol_pos'   => 'right_space',
				'num_decimals' => 2,
				'decimal_sep'  => ',',
				'thousand_sep' => '.',
			),
			'ERN' => array(
				'name'         => 'Eritrean nakfa',
				'singular'     => 'Eritrean nakfa',
				'plural'       => 'Eritrean nakfas',
				'symbol'       => null,
				'symbol_pos'   => 'left',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'ETB' => array(
				'name'         => 'Ethiopian birr',
				'singular'     => 'Ethiopian birr',
				'plural'       => 'Ethiopian birrs',
				'symbol'       => null,
				'symbol_pos'   => 'left',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'EUR' => array(
				'name'         => 'Euro',
				'singular'     => 'euro',
				'plural'       => 'euros',
				'symbol'       => '€',
				'symbol_pos'   => 'right_space',
				'num_decimals' => 2,
				'decimal_sep'  => ',',
				'thousand_sep' => '.',
			),
			'FKP' => array(
				'name'         => 'Falkland Islands pound',
				'singular'     => 'Falkland Islands pound',
				'plural'       => 'Falkland Islands pounds',
				'symbol'       => '£',
				'symbol_pos'   => 'left',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'FJD' => array(
				'name'         => 'Fijian dollar',
				'singular'     => 'Fijian dollar',
				'plural'       => 'Fijian dollars',
				'symbol'       => '$',
				'symbol_pos'   => 'left',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'GMD' => array(
				'name'         => 'Gambian dalasi',
				'singular'     => 'Gambian dalasi',
				'plural'       => 'Gambian dalasis',
				'symbol'       => null,
				'symbol_pos'   => 'left',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'GEL' => array(
				'name'         => 'Georgian lari',
				'singular'     => 'Georgian lari',
				'plural'       => 'Georgian laris',
				'symbol'       => '₾',
				'symbol_pos'   => 'right_space',
				'num_decimals' => 2,
				'decimal_sep'  => ',',
				'thousand_sep' => ' ',
			),
			'GHS' => array(
				'name'         => 'Ghana cedi',
				'singular'     => 'Ghanaian cedi',
				'plural'       => 'Ghanaian cedis',
				'symbol'       => 'GH₵',
				'symbol_pos'   => 'left',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'GIP' => array(
				'name'         => 'Gibraltar pound',
				'singular'     => 'Gibraltar pound',
				'plural'       => 'Gibraltar pounds',
				'symbol'       => '£',
				'symbol_pos'   => 'left',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'GTQ' => array(
				'name'         => 'Guatemalan quetzal',
				'singular'     => 'Guatemalan quetzal',
				'plural'       => 'Guatemalan quetzals',
				'symbol'       => 'Q',
				'symbol_pos'   => 'left',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'GNF' => array(
				'name'         => 'Guinean franc',
				'singular'     => 'Guinean franc',
				'plural'       => 'Guinean francs',
				'symbol'       => 'FG',
				'symbol_pos'   => 'right_space',
				'num_decimals' => 0,
				'decimal_sep'  => ',',
				'thousand_sep' => ' ',
			),
			'GYD' => array(
				'name'         => 'Guyanese dollar',
				'singular'     => 'Guyanaese dollar',
				'plural'       => 'Guyanaese dollars',
				'symbol'       => '$',
				'symbol_pos'   => 'left',
				'num_decimals' => 0,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'HNL' => array(
				'name'         => 'Honduran lempira',
				'singular'     => 'Honduran lempira',
				'plural'       => 'Honduran lempiras',
				'symbol'       => 'L',
				'symbol_pos'   => 'left',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'HKD' => array(
				'name'         => 'Hong Kong dollar',
				'singular'     => 'Hong Kong dollar',
				'plural'       => 'Hong Kong dollars',
				'symbol'       => '$',
				'symbol_pos'   => 'left',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'HUF' => array(
				'name'         => 'Hungarian forint',
				'singular'     => 'Hungarian forint',
				'plural'       => 'Hungarian forints',
				'symbol'       => 'Ft',
				'symbol_pos'   => 'right_space',
				'num_decimals' => 0,
				'decimal_sep'  => ',',
				'thousand_sep' => ' ',
			),
			'ISK' => array(
				'name'         => 'Icelandic króna',
				'singular'     => 'Icelandic króna',
				'plural'       => 'Icelandic krónur',
				'symbol'       => 'kr',
				'symbol_pos'   => 'right_space',
				'num_decimals' => 0,
				'decimal_sep'  => ',',
				'thousand_sep' => '.',
			),
			'INR' => array(
				'name'         => 'Indian rupee',
				'singular'     => 'Indian rupee',
				'plural'       => 'Indian rupees',
				'symbol'       => '₹',
				'symbol_pos'   => 'left',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'IDR' => array(
				'name'         => 'Indonesian rupiah',
				'singular'     => 'Indonesian rupiah',
				'plural'       => 'Indonesian rupiahs',
				'symbol'       => 'Rp',
				'symbol_pos'   => 'left',
				'num_decimals' => 0,
				'decimal_sep'  => ',',
				'thousand_sep' => '.',
			),
			'IRR' => array(
				'name'         => 'Iranian rial',
				'singular'     => 'Iranian rial',
				'plural'       => 'Iranian rials',
				'symbol'       => null,
				'symbol_pos'   => 'left',
				'num_decimals' => 0,
				'decimal_sep'  => ',',
				'thousand_sep' => '.',
			),
			'IQD' => array(
				'name'         => 'Iraqi dinar',
				'singular'     => 'Iraqi dinar',
				'plural'       => 'Iraqi dinars',
				'symbol'       => null,
				'symbol_pos'   => 'right_space',
				'num_decimals' => 0,
				'decimal_sep'  => ',',
				'thousand_sep' => '.',
			),
			'ILS' => array(
				'name'         => 'Israeli new shekel',
				'singular'     => 'Israeli new shekel',
				'plural'       => 'Israeli new shekels',
				'symbol'       => '₪',
				'symbol_pos'   => 'right_space',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'JMD' => array(
				'name'         => 'Jamaican dollar',
				'singular'     => 'Jamaican dollar',
				'plural'       => 'Jamaican dollars',
				'symbol'       => '$',
				'symbol_pos'   => 'left',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'JPY' => array(
				'name'         => 'Japanese yen',
				'singular'     => 'Japanese yen',
				'plural'       => 'Japanese yen',
				'symbol'       => '¥',
				'symbol_pos'   => 'left',
				'num_decimals' => 0,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'JOD' => array(
				'name'         => 'Jordanian dinar',
				'singular'     => 'Jordanian dinar',
				'plural'       => 'Jordanian dinars',
				'symbol'       => null,
				'symbol_pos'   => 'right_space',
				'num_decimals' => 3,
				'decimal_sep'  => ',',
				'thousand_sep' => '.',
			),
			'KZT' => array(
				'name'         => 'Kazakhstani tenge',
				'singular'     => 'Kazakhstani tenge',
				'plural'       => 'Kazakhstani tenges',
				'symbol'       => '₸',
				'symbol_pos'   => 'right_space',
				'num_decimals' => 2,
				'decimal_sep'  => ',',
				'thousand_sep' => ' ',
			),
			'KES' => array(
				'name'         => 'Kenyan shilling',
				'singular'     => 'Kenyan shilling',
				'plural'       => 'Kenyan shillings',
				'symbol'       => null,
				'symbol_pos'   => 'left_space',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'KWD' => array(
				'name'         => 'Kuwaiti dinar',
				'singular'     => 'Kuwaiti dinar',
				'plural'       => 'Kuwaiti dinars',
				'symbol'       => null,
				'symbol_pos'   => 'right_space',
				'num_decimals' => 3,
				'decimal_sep'  => ',',
				'thousand_sep' => '.',
			),
			'KGS' => array(
				'name'         => 'Kyrgyzstani som',
				'singular'     => 'Kyrgystani som',
				'plural'       => 'Kyrgystani soms',
				'symbol'       => null,
				'symbol_pos'   => 'right_space',
				'num_decimals' => 2,
				'decimal_sep'  => ',',
				'thousand_sep' => ' ',
			),
			'LAK' => array(
				'name'         => 'Lao kip',
				'singular'     => 'Laotian kip',
				'plural'       => 'Laotian kips',
				'symbol'       => '₭',
				'symbol_pos'   => 'left',
				'num_decimals' => 0,
				'decimal_sep'  => ',',
				'thousand_sep' => '.',
			),
			'LBP' => array(
				'name'         => 'Lebanese pound',
				'singular'     => 'Lebanese pound',
				'plural'       => 'Lebanese pounds',
				'symbol'       => 'L£',
				'symbol_pos'   => 'right_space',
				'num_decimals' => 0,
				'decimal_sep'  => ',',
				'thousand_sep' => '.',
			),
			'LSL' => array(
				'name'         => 'Lesotho loti',
				'singular'     => 'Lesotho loti',
				'plural'       => 'Lesotho lotis',
				'symbol'       => null,
				'symbol_pos'   => 'left',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'LRD' => array(
				'name'         => 'Liberian dollar',
				'singular'     => 'Liberian dollar',
				'plural'       => 'Liberian dollars',
				'symbol'       => '$',
				'symbol_pos'   => 'left',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'LYD' => array(
				'name'         => 'Libyan dinar',
				'singular'     => 'Libyan dinar',
				'plural'       => 'Libyan dinars',
				'symbol'       => null,
				'symbol_pos'   => 'left_space',
				'num_decimals' => 3,
				'decimal_sep'  => ',',
				'thousand_sep' => '.',
			),
			'MOP' => array(
				'name'         => 'Macanese pataca',
				'singular'     => 'Macanese pataca',
				'plural'       => 'Macanese patacas',
				'symbol'       => null,
				'symbol_pos'   => 'left',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'MKD' => array(
				'name'         => 'Macedonian denar',
				'singular'     => 'Macedonian denar',
				'plural'       => 'Macedonian denari',
				'symbol'       => null,
				'symbol_pos'   => 'right_space',
				'num_decimals' => 2,
				'decimal_sep'  => ',',
				'thousand_sep' => '.',
			),
			'MGA' => array(
				'name'         => 'Malagasy ariary',
				'singular'     => 'Malagasy ariary',
				'plural'       => 'Malagasy ariaries',
				'symbol'       => 'Ar',
				'symbol_pos'   => 'left_space',
				'num_decimals' => 0,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'MWK' => array(
				'name'         => 'Malawian kwacha',
				'singular'     => 'Malawian kwacha',
				'plural'       => 'Malawian kwachas',
				'symbol'       => null,
				'symbol_pos'   => 'left',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'MYR' => array(
				'name'         => 'Malaysian ringgit',
				'singular'     => 'Malaysian ringgit',
				'plural'       => 'Malaysian ringgits',
				'symbol'       => 'RM',
				'symbol_pos'   => 'left',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'MVR' => array(
				'name'         => 'Maldivian rufiyaa',
				'singular'     => 'Maldivian rufiyaa',
				'plural'       => 'Maldivian rufiyaas',
				'symbol'       => null,
				'symbol_pos'   => 'left_space',
				'num_decimals' => 2,
				'decimal_sep'  => ',',
				'thousand_sep' => '.',
			),
			'MRU' => array(
				'name'         => 'Mauritanian ouguiya',
				'singular'     => 'Mauritanian ouguiya',
				'plural'       => 'Mauritanian ouguiyas',
				'symbol'       => null,
				'symbol_pos'   => 'right_space',
				'num_decimals' => 2,
				'decimal_sep'  => ',',
				'thousand_sep' => '.',
			),
			'MUR' => array(
				'name'         => 'Mauritian rupee',
				'singular'     => 'Mauritian rupee',
				'plural'       => 'Mauritian rupees',
				'symbol'       => 'Rs',
				'symbol_pos'   => 'left',
				'num_decimals' => 0,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'MXN' => array(
				'name'         => 'Mexican peso',
				'singular'     => 'Mexican peso',
				'plural'       => 'Mexican pesos',
				'symbol'       => '$',
				'symbol_pos'   => 'left',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'MDL' => array(
				'name'         => 'Moldovan leu',
				'singular'     => 'Moldovan leu',
				'plural'       => 'Moldovan lei',
				'symbol'       => null,
				'symbol_pos'   => 'right_space',
				'num_decimals' => 2,
				'decimal_sep'  => ',',
				'thousand_sep' => '.',
			),
			'MNT' => array(
				'name'         => 'Mongolian tögrög',
				'singular'     => 'Mongolian tugrik',
				'plural'       => 'Mongolian tugriks',
				'symbol'       => '₮',
				'symbol_pos'   => 'left_space',
				'num_decimals' => 0,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'MAD' => array(
				'name'         => 'Moroccan dirham',
				'singular'     => 'Moroccan dirham',
				'plural'       => 'Moroccan dirhams',
				'symbol'       => null,
				'symbol_pos'   => 'left_space',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'MZN' => array(
				'name'         => 'Mozambican metical',
				'singular'     => 'Mozambican metical',
				'plural'       => 'Mozambican meticals',
				'symbol'       => null,
				'symbol_pos'   => 'right_space',
				'num_decimals' => 2,
				'decimal_sep'  => ',',
				'thousand_sep' => ' ',
			),
			'NAD' => array(
				'name'         => 'Namibian dollar',
				'singular'     => 'Namibian dollar',
				'plural'       => 'Namibian dollars',
				'symbol'       => '$',
				'symbol_pos'   => 'left',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'NPR' => array(
				'name'         => 'Nepalese rupee',
				'singular'     => 'Nepalese rupee',
				'plural'       => 'Nepalese rupees',
				'symbol'       => 'Rs',
				'symbol_pos'   => 'left_space',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'ANG' => array(
				'name'         => 'Netherlands Antillean guilder',
				'singular'     => 'Netherlands Antillean guilder',
				'plural'       => 'Netherlands Antillean guilders',
				'symbol'       => null,
				'symbol_pos'   => 'left_space',
				'num_decimals' => 2,
				'decimal_sep'  => ',',
				'thousand_sep' => '.',
			),
			'TWD' => array(
				'name'         => 'New Taiwan dollar',
				'singular'     => 'New Taiwan dollar',
				'plural'       => 'New Taiwan dollars',
				'symbol'       => '$',
				'symbol_pos'   => 'left',
				'num_decimals' => 0,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'NZD' => array(
				'name'         => 'New Zealand dollar',
				'singular'     => 'New Zealand dollar',
				'plural'       => 'New Zealand dollars',
				'symbol'       => '$',
				'symbol_pos'   => 'left',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'NIO' => array(
				'name'         => 'Nicaraguan córdoba',
				'singular'     => 'Nicaraguan córdoba',
				'plural'       => 'Nicaraguan córdobas',
				'symbol'       => 'C$',
				'symbol_pos'   => 'left',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'NGN' => array(
				'name'         => 'Nigerian naira',
				'singular'     => 'Nigerian naira',
				'plural'       => 'Nigerian nairas',
				'symbol'       => '₦',
				'symbol_pos'   => 'left',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'KPW' => array(
				'name'         => 'North Korean won',
				'singular'     => 'North Korean won',
				'plural'       => 'North Korean won',
				'symbol'       => '₩',
				'symbol_pos'   => 'left',
				'num_decimals' => 0,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'NOK' => array(
				'name'         => 'Norwegian krone',
				'singular'     => 'Norwegian krone',
				'plural'       => 'Norwegian kroner',
				'symbol'       => 'kr',
				'symbol_pos'   => 'left_space',
				'num_decimals' => 0,
				'decimal_sep'  => ',',
				'thousand_sep' => ' ',
			),
			'OMR' => array(
				'name'         => 'Omani rial',
				'singular'     => 'Omani rial',
				'plural'       => 'Omani rials',
				'symbol'       => null,
				'symbol_pos'   => 'right_space',
				'num_decimals' => 3,
				'decimal_sep'  => ',',
				'thousand_sep' => '.',
			),
			'PKR' => array(
				'name'         => 'Pakistani rupee',
				'singular'     => 'Pakistani rupee',
				'plural'       => 'Pakistani rupees',
				'symbol'       => 'Rs',
				'symbol_pos'   => 'left_space',
				'num_decimals' => 0,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'PGK' => array(
				'name'         => 'Papua New Guinean kina',
				'singular'     => 'Papua New Guinean kina',
				'plural'       => 'Papua New Guinean kina',
				'symbol'       => null,
				'symbol_pos'   => 'left',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'PYG' => array(
				'name'         => 'Paraguayan guaraní',
				'singular'     => 'Paraguayan guarani',
				'plural'       => 'Paraguayan guaranis',
				'symbol'       => '₲',
				'symbol_pos'   => 'left_space',
				'num_decimals' => 0,
				'decimal_sep'  => ',',
				'thousand_sep' => '.',
			),
			'PHP' => array(
				'name'         => 'Philippine peso',
				'singular'     => 'Philippine piso',
				'plural'       => 'Philippine pisos',
				'symbol'       => '₱',
				'symbol_pos'   => 'left',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'PLN' => array(
				'name'         => 'Polish złoty',
				'singular'     => 'Polish zloty',
				'plural'       => 'Polish zlotys',
				'symbol'       => 'zł',
				'symbol_pos'   => 'right_space',
				'num_decimals' => 2,
				'decimal_sep'  => ',',
				'thousand_sep' => ' ',
			),
			'GBP' => array(
				'name'         => 'Pound sterling',
				'singular'     => 'British pound',
				'plural'       => 'British pounds',
				'symbol'       => '£',
				'symbol_pos'   => 'left',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'QAR' => array(
				'name'         => 'Qatari riyal',
				'singular'     => 'Qatari rial',
				'plural'       => 'Qatari rials',
				'symbol'       => null,
				'symbol_pos'   => 'right_space',
				'num_decimals' => 2,
				'decimal_sep'  => ',',
				'thousand_sep' => '.',
			),
			'RON' => array(
				'name'         => 'Romanian leu',
				'singular'     => 'Romanian leu',
				'plural'       => 'Romanian lei',
				'symbol'       => 'lei',
				'symbol_pos'   => 'right_space',
				'num_decimals' => 2,
				'decimal_sep'  => ',',
				'thousand_sep' => '.',
			),
			'RUB' => array(
				'name'         => 'Russian ruble',
				'singular'     => 'Russian ruble',
				'plural'       => 'Russian rubles',
				'symbol'       => '₽',
				'symbol_pos'   => 'right_space',
				'num_decimals' => 2,
				'decimal_sep'  => ',',
				'thousand_sep' => ' ',
			),
			'RWF' => array(
				'name'         => 'Rwandan franc',
				'singular'     => 'Rwandan franc',
				'plural'       => 'Rwandan francs',
				'symbol'       => 'RF',
				'symbol_pos'   => 'left_space',
				'num_decimals' => 0,
				'decimal_sep'  => ',',
				'thousand_sep' => '.',
			),
			'SHP' => array(
				'name'         => 'Saint Helena pound',
				'singular'     => 'St. Helena pound',
				'plural'       => 'St. Helena pounds',
				'symbol'       => '£',
				'symbol_pos'   => 'left',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'WST' => array(
				'name'         => 'Samoan tālā',
				'singular'     => 'Samoan tala',
				'plural'       => 'Samoan tala',
				'symbol'       => null,
				'symbol_pos'   => 'left',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'SAR' => array(
				'name'         => 'Saudi riyal',
				'singular'     => 'Saudi riyal',
				'plural'       => 'Saudi riyals',
				'symbol'       => null,
				'symbol_pos'   => 'right_space',
				'num_decimals' => 2,
				'decimal_sep'  => ',',
				'thousand_sep' => '.',
			),
			'RSD' => array(
				'name'         => 'Serbian dinar',
				'singular'     => 'Serbian dinar',
				'plural'       => 'Serbian dinars',
				'symbol'       => null,
				'symbol_pos'   => 'right_space',
				'num_decimals' => 0,
				'decimal_sep'  => ',',
				'thousand_sep' => '.',
			),
			'SCR' => array(
				'name'         => 'Seychellois rupee',
				'singular'     => 'Seychellois rupee',
				'plural'       => 'Seychellois rupees',
				'symbol'       => null,
				'symbol_pos'   => 'right_space',
				'num_decimals' => 2,
				'decimal_sep'  => ',',
				'thousand_sep' => ' ',
			),
			'SLL' => array(
				'name'         => 'Sierra Leonean leone',
				'singular'     => 'Sierra Leonean leone',
				'plural'       => 'Sierra Leonean leones',
				'symbol'       => null,
				'symbol_pos'   => 'left',
				'num_decimals' => 0,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'SGD' => array(
				'name'         => 'Singapore dollar',
				'singular'     => 'Singapore dollar',
				'plural'       => 'Singapore dollars',
				'symbol'       => '$',
				'symbol_pos'   => 'left',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'PEN' => array(
				'name'         => 'Sol',
				'singular'     => 'Peruvian sol',
				'plural'       => 'Peruvian soles',
				'symbol'       => null,
				'symbol_pos'   => 'left_space',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'SBD' => array(
				'name'         => 'Solomon Islands dollar',
				'singular'     => 'Solomon Islands dollar',
				'plural'       => 'Solomon Islands dollars',
				'symbol'       => '$',
				'symbol_pos'   => 'left',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'SOS' => array(
				'name'         => 'Somali shilling',
				'singular'     => 'Somali shilling',
				'plural'       => 'Somali shillings',
				'symbol'       => null,
				'symbol_pos'   => 'left',
				'num_decimals' => 0,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'ZAR' => array(
				'name'         => 'South African rand',
				'singular'     => 'South African rand',
				'plural'       => 'South African rand',
				'symbol'       => 'R',
				'symbol_pos'   => 'left',
				'num_decimals' => 2,
				'decimal_sep'  => ',',
				'thousand_sep' => ' ',
			),
			'KRW' => array(
				'name'         => 'South Korean won',
				'singular'     => 'South Korean won',
				'plural'       => 'South Korean won',
				'symbol'       => '₩',
				'symbol_pos'   => 'left',
				'num_decimals' => 0,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'SSP' => array(
				'name'         => 'South Sudanese pound',
				'singular'     => 'South Sudanese pound',
				'plural'       => 'South Sudanese pounds',
				'symbol'       => '£',
				'symbol_pos'   => 'left',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'LKR' => array(
				'name'         => 'Sri Lankan rupee',
				'singular'     => 'Sri Lankan rupee',
				'plural'       => 'Sri Lankan rupees',
				'symbol'       => 'Rs',
				'symbol_pos'   => 'left',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'SDG' => array(
				'name'         => 'Sudanese pound',
				'singular'     => 'Sudanese pound',
				'plural'       => 'Sudanese pounds',
				'symbol'       => null,
				'symbol_pos'   => 'right_space',
				'num_decimals' => 2,
				'decimal_sep'  => ',',
				'thousand_sep' => '.',
			),
			'SRD' => array(
				'name'         => 'Surinamese dollar',
				'singular'     => 'Surinamese dollar',
				'plural'       => 'Surinamese dollars',
				'symbol'       => '$',
				'symbol_pos'   => 'left_space',
				'num_decimals' => 2,
				'decimal_sep'  => ',',
				'thousand_sep' => '.',
			),
			'SZL' => array(
				'name'         => 'Swazi lilangeni',
				'singular'     => 'Swazi lilangeni',
				'plural'       => 'Swazi emalangeni',
				'symbol'       => null,
				'symbol_pos'   => 'left',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'SEK' => array(
				'name'         => 'Swedish krona',
				'singular'     => 'Swedish krona',
				'plural'       => 'Swedish kronor',
				'symbol'       => 'kr',
				'symbol_pos'   => 'right_space',
				'num_decimals' => 0,
				'decimal_sep'  => ',',
				'thousand_sep' => ' ',
			),
			'CHF' => array(
				'name'         => 'Swiss franc',
				'singular'     => 'Swiss franc',
				'plural'       => 'Swiss francs',
				'symbol'       => null,
				'symbol_pos'   => 'left_space',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => '\'',
			),
			'SYP' => array(
				'name'         => 'Syrian pound',
				'singular'     => 'Syrian pound',
				'plural'       => 'Syrian pounds',
				'symbol'       => '£',
				'symbol_pos'   => 'right_space',
				'num_decimals' => 0,
				'decimal_sep'  => ',',
				'thousand_sep' => '.',
			),
			'STN' => array(
				'name'         => 'São Tomé and Príncipe dobra',
				'singular'     => 'São Tomé & Príncipe dobra',
				'plural'       => 'São Tomé & Príncipe dobras',
				'symbol'       => 'Db',
				'symbol_pos'   => 'right_space',
				'num_decimals' => 2,
				'decimal_sep'  => ',',
				'thousand_sep' => ' ',
			),
			'TJS' => array(
				'name'         => 'Tajikistani somoni',
				'singular'     => 'Tajikistani somoni',
				'plural'       => 'Tajikistani somonis',
				'symbol'       => null,
				'symbol_pos'   => 'right_space',
				'num_decimals' => 2,
				'decimal_sep'  => ',',
				'thousand_sep' => ' ',
			),
			'TZS' => array(
				'name'         => 'Tanzanian shilling',
				'singular'     => 'Tanzanian shilling',
				'plural'       => 'Tanzanian shillings',
				'symbol'       => null,
				'symbol_pos'   => 'left_space',
				'num_decimals' => 0,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'THB' => array(
				'name'         => 'Thai baht',
				'singular'     => 'Thai baht',
				'plural'       => 'Thai baht',
				'symbol'       => '฿',
				'symbol_pos'   => 'left',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'TOP' => array(
				'name'         => 'Tongan paʻanga',
				'singular'     => 'Tongan paʻanga',
				'plural'       => 'Tongan paʻanga',
				'symbol'       => 'T$',
				'symbol_pos'   => 'left_space',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'TTD' => array(
				'name'         => 'Trinidad and Tobago dollar',
				'singular'     => 'Trinidad & Tobago dollar',
				'plural'       => 'Trinidad & Tobago dollars',
				'symbol'       => '$',
				'symbol_pos'   => 'left',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'TND' => array(
				'name'         => 'Tunisian dinar',
				'singular'     => 'Tunisian dinar',
				'plural'       => 'Tunisian dinars',
				'symbol'       => null,
				'symbol_pos'   => 'left_space',
				'num_decimals' => 3,
				'decimal_sep'  => ',',
				'thousand_sep' => '.',
			),
			'TRY' => array(
				'name'         => 'Turkish lira',
				'singular'     => 'Turkish lira',
				'plural'       => 'Turkish Lira',
				'symbol'       => '₺',
				'symbol_pos'   => 'left',
				'num_decimals' => 2,
				'decimal_sep'  => ',',
				'thousand_sep' => '.',
			),
			'TMT' => array(
				'name'         => 'Turkmenistan manat',
				'singular'     => 'Turkmenistani manat',
				'plural'       => 'Turkmenistani manat',
				'symbol'       => null,
				'symbol_pos'   => 'right_space',
				'num_decimals' => 2,
				'decimal_sep'  => ',',
				'thousand_sep' => ' ',
			),
			'UGX' => array(
				'name'         => 'Ugandan shilling',
				'singular'     => 'Ugandan shilling',
				'plural'       => 'Ugandan shillings',
				'symbol'       => null,
				'symbol_pos'   => 'left_space',
				'num_decimals' => 0,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'UAH' => array(
				'name'         => 'Ukrainian hryvnia',
				'singular'     => 'Ukrainian hryvnia',
				'plural'       => 'Ukrainian hryvnias',
				'symbol'       => '₴',
				'symbol_pos'   => 'right_space',
				'num_decimals' => 2,
				'decimal_sep'  => ',',
				'thousand_sep' => ' ',
			),
			'AED' => array(
				'name'         => 'United Arab Emirates dirham',
				'singular'     => 'UAE dirham',
				'plural'       => 'UAE dirhams',
				'symbol'       => null,
				'symbol_pos'   => 'right_space',
				'num_decimals' => 2,
				'decimal_sep'  => ',',
				'thousand_sep' => '.',
			),
			'USD' => array(
				'name'         => 'United States (US) dollar',
				'singular'     => 'US dollar',
				'plural'       => 'US dollars',
				'symbol'       => '$',
				'symbol_pos'   => 'left',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'UYU' => array(
				'name'         => 'Uruguayan peso',
				'singular'     => 'Uruguayan peso',
				'plural'       => 'Uruguayan pesos',
				'symbol'       => '$',
				'symbol_pos'   => 'left_space',
				'num_decimals' => 2,
				'decimal_sep'  => ',',
				'thousand_sep' => '.',
			),
			'UZS' => array(
				'name'         => 'Uzbekistani som',
				'singular'     => 'Uzbekistani som',
				'plural'       => 'Uzbekistani som',
				'symbol'       => null,
				'symbol_pos'   => 'right_space',
				'num_decimals' => 0,
				'decimal_sep'  => ',',
				'thousand_sep' => ' ',
			),
			'VUV' => array(
				'name'         => 'Vanuatu vatu',
				'singular'     => 'Vanuatu vatu',
				'plural'       => 'Vanuatu vatus',
				'symbol'       => null,
				'symbol_pos'   => 'left',
				'num_decimals' => 0,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
			'VND' => array(
				'name'         => 'Vietnamese đồng',
				'singular'     => 'Vietnamese dong',
				'plural'       => 'Vietnamese dong',
				'symbol'       => '₫',
				'symbol_pos'   => 'right_space',
				'num_decimals' => 0,
				'decimal_sep'  => ',',
				'thousand_sep' => '.',
			),
			'XOF' => array(
				'name'         => 'West African CFA franc',
				'singular'     => 'West African CFA franc',
				'plural'       => 'West African CFA francs',
				'symbol'       => null,
				'symbol_pos'   => 'right_space',
				'num_decimals' => 0,
				'decimal_sep'  => ',',
				'thousand_sep' => ' ',
			),
			'YER' => array(
				'name'         => 'Yemeni rial',
				'singular'     => 'Yemeni rial',
				'plural'       => 'Yemeni rials',
				'symbol'       => null,
				'symbol_pos'   => 'right_space',
				'num_decimals' => 0,
				'decimal_sep'  => ',',
				'thousand_sep' => '.',
			),
			'ZMW' => array(
				'name'         => 'Zambian kwacha',
				'singular'     => 'Zambian kwacha',
				'plural'       => 'Zambian kwachas',
				'symbol'       => 'ZK',
				'symbol_pos'   => 'left',
				'num_decimals' => 2,
				'decimal_sep'  => '.',
				'thousand_sep' => ',',
			),
		);
	}

}
